#!/usr/bin/env bash

current_version=$(vagrant -v | awk '{print $2}')

echo "Switching from vagrant v$current_version to v$1"

vagrant_path="/Applications/Vagrant-$1"

if [[ "$current_version" == "$1" ]]; then
  echo "Already on vagrant v$current_version"
elif [[ -d "$vagrant_path" ]]; then
mv /Applications/Vagrant /Applications/Vagrant-$current_version && \
  mv ~/.vagrant.d ~/.vagrant.d-$current_version && \
  mv ~/.berkshelf ~/.berkshelf-$current_version && \
  mv /Applications/Vagrant-$1 /Applications/Vagrant && \
  mv ~/.vagrant.d-$1 ~/.vagrant.d && \
  mv ~/.berkshelf-$1 ~/.berkshelf

  echo "Switched from vagrant v$current_version to v$1"
else
  echo "Could not find vagrant $1"
fi
